apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-ai
  template:
    metadata:
      labels:
        app: fastapi-ai
    spec:
      containers:
      - name: fastapi-ai
        image: python:3.11
        command: ["/bin/sh"]
        args:
          - -c
          - pip install -r /app/requirements.txt && uvicorn main:app --host 0.0.0.0 --port 3000
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: app-code
          mountPath: /app
        envFrom:
        - secretRef:
            name: flask-secrets
      volumes:
      - name: app-code
        configMap:
          name: flask-app-files
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-ai-service
spec:
  type: LoadBalancer
  selector:
    app: fastapi-ai
  ports:
  - port: 80
    targetPort: 3000
