apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-agent-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: ai-agent
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
